### ISSUE TITLE
iOptron 64-bit X2 Mount Plug In Libraries Not Distributed

### ISSUE THREAD

**Issue by dbisque** [rpineau/iOptronV3#1]
The iOptronV3_X2_Installer.exe Version 1.3 does not distribute the 64-bit binaries to \PlugIns64\MountPlugIns folder.  

Can you please update the installer to include them?

Thanks!!

**Comment by rpineau** [comment]
The current installer does install the plugin for 64 bits...., IF TSX has been run in 32 bit mode once :) ... but I do have a fix for this and will publish the new installer today.

**Comment by rpineau** [comment]
1.4 has been pushed. I tested the install by removing the plugin and all related file from my windows machine and also removed the TheSkyXInstallPath.txt from the 32 bit version. It founds the TheSkyXInstallPath.txt in the 64 bit user data and installs both.

**Comment by dbisque** [comment]
Rodolphe,

That was fast, thanks for responding so quickly!

>>
IF TSX has been run in 32 bit mode once :)
<<

Sorry!  I did not know this necessary step.  (I too often don’t run TheSky 32-bit.  Doh!)

Sincerely,

Dan

**Comment by rpineau** [comment]
With the new installer no need to run TSX 32 bit first anymore.
